---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-purple
spec:
  replicas: 3
  selector:
    matchLabels:
      color: purple
  template:
    metadata:
      labels:
        color: purple
    spec:
      containers:
      - name: ctn-purple
        image: dododong478/keduitlab:purple
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name:  myrepo

---
apiVersion: v1
kind: Service
metadata:
  name: purple-lb
spec:
  selector:
    color: purple
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer